import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { K3GeneratedModule, K3GeneratedSharedModule } from './generated/module.js';
import { K3Validator, registerValidationChecks } from './k3-validator.js';
import { K3SemanticTokens } from './k3-semantic-tokens.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type K3AddedServices = {
    validation: {
        K3Validator: K3Validator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type K3Services = LangiumServices & K3AddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const K3Module: Module<K3Services, PartialLangiumServices & K3AddedServices> = {
    validation: { K3Validator: () => new K3Validator() },
    lsp: { SemanticTokenProvider: services=> new K3SemanticTokens(services) }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createK3Services(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    K3: K3Services
} {
    const shared = inject(
        createDefaultSharedModule(context),
        K3GeneratedSharedModule
    );
    const K3 = inject(
        createDefaultModule({ shared }),
        K3GeneratedModule,
        K3Module
    );
    shared.ServiceRegistry.register(K3);
    registerValidationChecks(K3);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, K3 };
}
